
language: elixir

elixir:
  - 1.9.0
  - 1.9.1
  - 1.9.2
  - 1.9.3
  - 1.9.4
  - 1.10.0
  - 1.10.1
  - 1.10.2
  - 1.10.3
otp_release:
  - 21.0
  - 22.3

matrix:
  include:
    # Elixir format
    - elixir: 1.9.1
      script:
        - mix format --check-formatted
      env: CHECK_FORMAT=TRUE
    # Elixir credo
    - elixir: 1.9.1
      script:
        - mix credo --strict
      env: CHECK_SYNTAX=TRUE
  allow_failures:
    - env: CHECK_SYNTAX=TRUE

dist: trusty

addons:
  postgresql: "9.6"

services:
  - rabbitmq

env:
  - MIX_ENV=test

install:
  - echo "use Mix.Config" > config/dev.secret.exs
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - curl -o- -L https://yarnpkg.com/install.sh | sh -s -- --version 1.9.4

before_script:
  - psql -c 'create database ex_subtil_backend_test;' -U postgres
  - mkdir -p priv/repo/migrations
  - mkdir -p deps/step_flow/priv/repo/migrations
  - echo -n 0.0.0 > VERSION

scripts:
  - mix test
  - cd assets && ../yarn && ../yarn run lint && ../yarn run release

notifications:
  slack:
    secure: lEnXJessDb7IkXaFox81yd2EqWWu7jIDczHZQY8ueIaaeJkb1GJdYZabEPAgFM6Y+ES0jPPXC+G/GkDbtRVLWi1TK687Dsb0uO4qdJm46S2QDZ6SjJvj7xT18qJDl2oqm9Ad8fWorpZUY4K0beDyZ9RQaP/6Fu9FMdq1JqvQrq9Pm2KI1LKoqRK/0YDkQ83zA/T8liIbELceFU8nGq2KG8aPGcfC4nlqJ1TyaGmuMHuGydXAL2I8wGZg+ydY8FUXgrxgFA4yC2G94NgLldcxps+WgLmcM2GqlKQLt+mlxUGdnnMLQ+J37eAzzS0mYdZPfnP01nIGoJGDHTobwPGo7fgG/3us/orb2R4UqoKa2KGEyujAXCRrn5c40+CMwxO5Epyguf9O3Og6ffx9hRs/1Z6izVOY+2AE1g4fEf7rvKhumHBrlAoMGv/27s/VDjpOg60lajALM9jvcCB19s5fCWVJEn8yIm49rd22xUmb9qc1xiEFZz2NZDJHGfMYUa4sY2fjQg5mmm8DjuGvr7cvmfByMHMBhXSayRTj+cbR/5ebKuIH2cZRmqkkeptkIaeyBBsL4WD/OJ1zK2sbEiH0hEy+IuzjNT/MPz7RbYYWjuHFvl0NIwNRZzcJ9nP5FkhfYGXRHtfbo/+ZN57q6kHwiTvU+t+OzoNMHPaIvMSw16M=
  email:
    recipients:
    - maarnaud@media-io.com
